// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLU1P4B6vkkJXXAmxYM0omz570e7-mTs',
    appId: '1:496738673476:web:2096ee374b5424b83fed11',
    messagingSenderId: '496738673476',
    projectId: 'social-network-90106',
    authDomain: 'social-network-90106.firebaseapp.com',
    databaseURL: 'https://social-network-90106-default-rtdb.firebaseio.com',
    storageBucket: 'social-network-90106.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUZKGq6lfijJTGnz7Ok8CM-v5Pr0WTCyk',
    appId: '1:496738673476:android:69d44496ade18f493fed11',
    messagingSenderId: '496738673476',
    projectId: 'social-network-90106',
    databaseURL: 'https://social-network-90106-default-rtdb.firebaseio.com',
    storageBucket: 'social-network-90106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4pNzuR9C6WC8DsTRaEB-hhVs9POoKRlo',
    appId: '1:496738673476:ios:dc083899b479af513fed11',
    messagingSenderId: '496738673476',
    projectId: 'social-network-90106',
    databaseURL: 'https://social-network-90106-default-rtdb.firebaseio.com',
    storageBucket: 'social-network-90106.firebasestorage.app',
    androidClientId:
        '496738673476-14nobrj7f01b75cg9m7tv3muln1cedlv.apps.googleusercontent.com',
    iosClientId:
        '496738673476-rg20rbc8ogi13kmlhr61u1j8adqjfus8.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialNetwork',
  );
}
